### ISSUE TITLE
EvaluateDeLUCS.py

### ISSUE THREAD

**Issue by gaushi** [millanp95/DeLUCS#4]
Hi,
Thanks for developing this tool!
While running EvaluateDeLUCS.py on test files (test 1) I got following error message:

**Traceback (most recent call last):
  File "EvaluateDeLUCS.py", line 3, in <module>
    import torch
  File "/src/python3/envs/delucs/lib/python3.7/site-packages/torch/__init__.py", line 84, in <module>
    from torch._C import *
ImportError: /src/python3/envs/delucs/lib/python3.7/site-packages/torch/lib/libmkldnn.so.0: undefined symbol: cblas_sgemm_alloc**

I tried to install mkl with intel (through conda install) and I am still getting the same error message.

Thanks,
Best regards,
Gautam

**Comment by millanp95** [comment]
Hi Gautam, 

I would recommend a clean installation of PyTorch through pip. Let me know if that does not help and we can troubleshoot further. 

Pablo

**Comment by gaushi** [comment]
Hi Pablo,
Thanks for the tip. I did the clean installation of PyTorch through pip. Now everything works!!. You can close the issue :)

Best,
Gautam
